source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'

use_frameworks!

target 'MMRtcKit_Example' do  
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'TPKeyboardAvoiding', '~> 1.3.1'
  pod 'Masonry', '~> 1.0.2'
  pod 'Bugly', '~> 2.5.71'
  pod 'Nama', '7.3.2'

  target 'MMRtcKit_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable bitcode in order to support cordova-plugin-iosrtc
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end
